-- MySQL Script generated by MySQL Workbench
-- jue 31 ene 2019 10:48:31 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=1;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=1;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema EMPACADORA
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `EMPACADORA` ;

-- -----------------------------------------------------
-- Schema EMPACADORA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EMPACADORA` DEFAULT CHARACTER SET utf8 ;
USE `EMPACADORA` ;

-- -----------------------------------------------------
-- Table `EMPACADORA`.`LOTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EMPACADORA`.`LOTE` ;

CREATE TABLE IF NOT EXISTS `EMPACADORA`.`LOTE` (
  `idlote` INT NOT NULL,
  `codigolote` VARCHAR(50) NOT NULL,
  `tipolote` VARCHAR(500) NOT NULL,
  `cantidadproductos` INT(11) NOT NULL,
  PRIMARY KEY (`idlote`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EMPACADORA`.`PRODUCTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EMPACADORA`.`PRODUCTO` ;

CREATE TABLE IF NOT EXISTS `EMPACADORA`.`PRODUCTO` (
  `codigoproducto` INT NOT NULL,
  `nombreproducto` VARCHAR(500) NOT NULL,
  `cantidadlitros` DOUBLE NOT NULL,
  `cantidadlitrosporunidad` DOUBLE NOT NULL,
  `LOTE_idlote` INT NOT NULL,
  PRIMARY KEY (`codigoproducto`),
  INDEX `fk_PRODUCTO_LOTE_idx` (`LOTE_idlote` ASC),
  CONSTRAINT `fk_PRODUCTO_LOTE`
    FOREIGN KEY (`LOTE_idlote`)
    REFERENCES `EMPACADORA`.`LOTE` (`idlote`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EMPACADORA`.`ESTADO_LOTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EMPACADORA`.`ESTADO_LOTE` ;

CREATE TABLE IF NOT EXISTS `EMPACADORA`.`ESTADO_LOTE` (
  `codigoestado` INT NOT NULL,
  `estadolote` TINYINT(1) NULL,
  `observacion` TEXT NULL,
  `LOTE_idlote` INT NOT NULL,
  PRIMARY KEY (`codigoestado`, `LOTE_idlote`),
  INDEX `fk_ESTADO_LOTE_LOTE1_idx` (`LOTE_idlote` ASC),
  CONSTRAINT `fk_ESTADO_LOTE_LOTE1`
    FOREIGN KEY (`LOTE_idlote`)
    REFERENCES `EMPACADORA`.`LOTE` (`idlote`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EMPACADORA`.`VENTAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EMPACADORA`.`VENTAS` ;

CREATE TABLE IF NOT EXISTS `EMPACADORA`.`VENTAS` (
  `codigoventa` INT NOT NULL AUTO_INCREMENT,
  `cantidadcomprada` INT(11) NOT NULL,
  `totalcompra` DOUBLE NOT NULL,
  PRIMARY KEY (`codigoventa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EMPACADORA`.`DETALLE_COMPRA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EMPACADORA`.`DETALLE_COMPRA` ;

CREATE TABLE IF NOT EXISTS `EMPACADORA`.`DETALLE_COMPRA` (
  `VENTAS_codigoventa` INT NOT NULL,
  `PRODUCTO_codigoproducto` INT NOT NULL,
  `fechacompra` DATETIME NOT NULL,
  `observacioncompra` TEXT NOT NULL,
  PRIMARY KEY (`VENTAS_codigoventa`, `PRODUCTO_codigoproducto`),
  INDEX `fk_VENTAS_has_PRODUCTO_PRODUCTO1_idx` (`PRODUCTO_codigoproducto` ASC),
  INDEX `fk_VENTAS_has_PRODUCTO_VENTAS1_idx` (`VENTAS_codigoventa` ASC),
  CONSTRAINT `fk_VENTAS_has_PRODUCTO_VENTAS1`
    FOREIGN KEY (`VENTAS_codigoventa`)
    REFERENCES `EMPACADORA`.`VENTAS` (`codigoventa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_VENTAS_has_PRODUCTO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_codigoproducto`)
    REFERENCES `EMPACADORA`.`PRODUCTO` (`codigoproducto`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
